### PR TITLE
Fixed a NullReferenceException in TryGiveJob.

### PR DESCRIPTION
**Pull request by ProfoundDarkness**
Specifically a situation where pawns not of player faction would try to find weapons with ammo.  Unfortunately that check assumed all weapons were ranged without limiting the list of weapons to ranged weapons (so the odd knife with no ammo could get included).

Also added a failover that if no ranged weapons with ammo are available they will try to grab a melee weapon instead.  Makes for some interesting prison breaks...

Retained the decent market value check in ranged weapons for melee so if all you've got is garbage melee weapons they probably won't walk off with one.

I tested both prison breaks and freed prisoners.  Both would grab a weapon if available though I'm not sure that would be desired behavior in the case of freed prisoners.  Looks like this fixes both issues in #78.

### CODE REVIEW

**Comment by Mythos** [comment]
Looks like it would also fix my problem in #87 .
I'll give it a try. ;-)

**Comment by Mythos** [comment]
After playing with these commits, my errors are gone.

**Comment by ProfoundDarkness** [comment]
I'm sorry, I don't know enough about git to fix the conflict.  Is there a recommended way that I submit PRs?  The most obvious would be to exclude binaries from my commits but then maintainers would have to run a compile to test/update the binary.

**Comment by Mythos** [comment]
Normally you don't include those binaries in the VCS.
In this case, it would be advisable that you merge the changes from the master-branch and you don't care about those 2 binaries (taking source or remote version doesn't matter).
Then you build your solution again, thus creating new versions of the two binaries and if you have new ones you can commit them. ;-)

**Comment by ProfoundDarkness** [comment]
OK, I didn't re-compile the binary, just 'used theirs' for the binary files and pushed that merge up to Looking_At_Prisoners branch.  Hopefully that will work on the other PR so they both stay merge-able.  From here on I won't include binaries in my PR commits.

Thanks.

**Comment by Mythos** [comment]
Unfortunately that is not enough, because "their" binaries don't include
your changes you made in the .cs files, because this pull request isn't
included in the master branch. ;-)

ProfoundDarkness <notifications@github.com> schrieb am Sa., 11. Feb. 2017,
09:11:

**Comment by ProfoundDarkness** [comment]
...? OK, now I'm really confused.  I did a standard merge on the text files (ie .cs) while using the master branch's binaries (overwriting my binaries).  Then pushed that up.  It says there are no conflicts now and I just looked on github, the changes I made to the .cs files are still present.

Do I actually need to do anything else considering it says no conflicts?

**Comment by Mythos** [comment]
Normally you need to recompile, because if you merge and you take "theirs", you are losing your changes, no matter which file it is. (Either binary or simple text file)
You might not have conflicts anymore, because you don't have two different versions of the same file anymore, but the binary now only contains the changes from the master-branch, so losing your changes if you didn't recompile after merging and before committing.

Are there changes if you recompile?

**Comment by ProfoundDarkness** [comment]
hmm... OK, first when I say binary I mean files like dll.  The program I'm using to handle git for me will automatically merge non-binary files no problem (if they can be automatically merged).  There isn't a problem merging the non-binary files on any of my 3 recent PRs.  So during the merge process, when it complained about the 2 .dll files I simply told it overwrite my dlls with theirs (theirs being this repo).

To answer the question: Yes, if I compile, a new binary is produced which is different.  Assuming my PRs are approved/merged the maintainer can run a compile to produce a new binary with all 3 changes (they seem to work fine together).  The alternate is once the maintainer merges one of my PRs I'll need to do another merge/resolve conflict before the other PR can be merged.

**Comment by Mythos** [comment]
I also mean .dll-Files with binaries.
Taking "your's" or "theirs" will remove changes accordingly. Normally you have to select the lines you want to keep, being "their's" or "your's". But this is not supported for binary files.
By taking "their's", this pull request has the .dll-Files of the master-branch, meaning, the .dll-Files need to be recreated after merging, or you do it now before merging.
Merging in this case -> accepting pull request.

As you have recompiled the project, you created new versions of the binaries, containing their **and** your changes.
Before you were taking "their" binary, meaning it only contained their changes and not your's anymore. ;-)

Unfortunately I'm not into modding in Rimworld and have no idea how publishing to Steam works, but normally you have a CI-Server which builds all the artifacts (e.g.  .dll-Files) and the repository only contains source code, thus preventing issues like these.

**Pull request merged**
